# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab6_AXI_Stream/Lab6_AXI_Stream.srcs/sources_1/ip/FP_Log/FP_Log.xci
# IP: The module: 'FP_Log' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab6_AXI_Stream/Lab6_AXI_Stream.srcs/sources_1/ip/FP_Log/FP_Log_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_Log'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab6_AXI_Stream/Lab6_AXI_Stream.srcs/sources_1/ip/FP_Log/FP_Log.xci
# IP: The module: 'FP_Log' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab6_AXI_Stream/Lab6_AXI_Stream.srcs/sources_1/ip/FP_Log/FP_Log_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_Log'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
