webtalk_init -webtalk_dir C:\\Users\\Riya_Sachdeva\\Desktop\\ELD_Lab\\Lab11_Multi_Stream\\Lab11_Multi_Stream.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2023-11-24 14:42:22" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bhabhchpl1mpkmhbbvsot1rp6j" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1498 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.850 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1700815678371" -context "sdk\\\\bsp/1700815678371"
webtalk_add_data -client sdk -key hwid -value "1700539878543" -context "sdk\\\\bsp/1700815678371"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1700815678371"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1700815678371"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1700815678371"
webtalk_add_data -client sdk -key uid -value "1700815680612" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key hwid -value "1700539878543" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key bspid -value "1700815678371" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key projSize -value "182.6015625" -context "sdk\\\\application/1700815680612"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1700817142694"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1700817142694"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1700817142694"
webtalk_add_data -client sdk -key DebugCount -value "15" -context "sdk\\\\bsp/1700817142694"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1700817142694"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1700817142694"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1700817142694"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1700817142694"
webtalk_transmit -clientid 3654658109 -regid "" -xml C:\\Users\\Riya_Sachdeva\\Desktop\\ELD_Lab\\Lab11_Multi_Stream\\Lab11_Multi_Stream.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Riya_Sachdeva\\Desktop\\ELD_Lab\\Lab11_Multi_Stream\\Lab11_Multi_Stream.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Riya_Sachdeva\\Desktop\\ELD_Lab\\Lab11_Multi_Stream\\Lab11_Multi_Stream.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
