# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab7_hw2/Lab7_hw2.srcs/sources_1/ip/FP_ln/FP_ln.xci
# IP: The module: 'FP_ln' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab7_hw2/Lab7_hw2.srcs/sources_1/ip/FP_ln/FP_ln_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_ln'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab7_hw2/Lab7_hw2.srcs/sources_1/ip/FP_ln/FP_ln.xci
# IP: The module: 'FP_ln' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab7_hw2/Lab7_hw2.srcs/sources_1/ip/FP_ln/FP_ln_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_ln'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
