# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab4_SequenceDetector/Lab4_SequenceDetector.srcs/sources_1/ip/clk_cmt/clk_cmt.xci
# IP: The module: 'clk_cmt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab4_SequenceDetector/Lab4_SequenceDetector.srcs/sources_1/ip/clk_cmt/clk_cmt_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_cmt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab4_SequenceDetector/Lab4_SequenceDetector.srcs/sources_1/ip/clk_cmt/clk_cmt.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab4_SequenceDetector/Lab4_SequenceDetector.srcs/sources_1/ip/clk_cmt/clk_cmt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab4_SequenceDetector/Lab4_SequenceDetector.srcs/sources_1/ip/clk_cmt/clk_cmt.xci
# IP: The module: 'clk_cmt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab4_SequenceDetector/Lab4_SequenceDetector.srcs/sources_1/ip/clk_cmt/clk_cmt_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab4_SequenceDetector/Lab4_SequenceDetector.srcs/sources_1/ip/clk_cmt/clk_cmt.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab4_SequenceDetector/Lab4_SequenceDetector.srcs/sources_1/ip/clk_cmt/clk_cmt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
