# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab7_FFT_IP/Lab7_FFT_IP.srcs/sources_1/ip/xfft_8/xfft_8.xci
# IP: The module: 'xfft_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab7_FFT_IP/Lab7_FFT_IP.srcs/sources_1/ip/xfft_8/xfft_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab7_FFT_IP/Lab7_FFT_IP.srcs/sources_1/ip/xfft_8/xfft_8.xci
# IP: The module: 'xfft_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab7_FFT_IP/Lab7_FFT_IP.srcs/sources_1/ip/xfft_8/xfft_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
