# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab5_DigClock/Lab5_DigClock.srcs/sources_1/ip/clk_div_to_8M/clk_div_to_8M.xci
# IP: The module: 'clk_div_to_8M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab5_DigClock/Lab5_DigClock.srcs/sources_1/ip/clk_div_to_8M/clk_div_to_8M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_to_8M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab5_DigClock/Lab5_DigClock.srcs/sources_1/ip/clk_div_to_8M/clk_div_to_8M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_to_8M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab5_DigClock/Lab5_DigClock.srcs/sources_1/ip/clk_div_to_8M/clk_div_to_8M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_to_8M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab5_DigClock/Lab5_DigClock.srcs/sources_1/ip/clk_div_to_8M/clk_div_to_8M.xci
# IP: The module: 'clk_div_to_8M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab5_DigClock/Lab5_DigClock.srcs/sources_1/ip/clk_div_to_8M/clk_div_to_8M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_to_8M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab5_DigClock/Lab5_DigClock.srcs/sources_1/ip/clk_div_to_8M/clk_div_to_8M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_to_8M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Riya_Sachdeva/Desktop/ELD_Lab/Lab5_DigClock/Lab5_DigClock.srcs/sources_1/ip/clk_div_to_8M/clk_div_to_8M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_to_8M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
