# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/zybo_const.xdc

# IP: ip/vio_0/vio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet
